title: ML Optimization (Grad)
author: OptimAI-Lab
copyright: "2025"
logo: ""
# html:
#   toc:
#     sidebar:
#       depth: 2
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    html_theme: sphinx_book_theme
    copyright: "2025"
    mathjax3_config:
      tex:
        macros:
          RR: "\\mathbb{R}"
          EE: "\\mathbb{E}"
          Var: "\\mathrm{Var}"
          KL: ["\\mathrm{KL}\\left(#1 \\middle\\| #2\\right)", 2]
    bibtex_reference_style: author_year  # or label
execute:
  execute_notebooks: "auto" # ["off", "auto"]